In [41]:
import pandas as pd

In [42]:
import openpyxl

In [43]:
i = 2008
boy_babyname = pd.DataFrame()
girl_babyname = pd.DataFrame()
boy = []
gitl = []
while True:
    try:
        boy_filename = "상위 출생신고 이름 현황_" + str(i) + "남.xls"
        girl_filename = "상위 출생신고 이름 현황_" + str(i) + "여.xls"
        nme = str(i)+"년 이름"
        boy = pd.read_excel("C:\\Users\\Admin\\Desktop\\name\\babyname\\" + boy_filename, header = 1, names = ['순위', nme, '전체비율', '건수'])
        girl = pd.read_excel("C:\\Users\\Admin\\Desktop\\name\\babyname\\" + girl_filename, header = 1, names = ['순위', nme, '전체비율', '건수'])
        print(i,"년 가져옴")
        boy_babyname = pd.concat([boy_babyname, boy],axis = 1)
        girl_babyname = pd.concat([girl_babyname,girl],axis = 1)
        i = i + 1
        print(i,"년 합침")
    except:
        print(i, "년 가져오다가 으악")
        break

2008 년 가져옴
2009 년 합침
2009 년 가져옴
2010 년 합침
2010 년 가져옴
2011 년 합침
2011 년 가져옴
2012 년 합침
2012 년 가져옴
2013 년 합침
2013 년 가져옴
2014 년 합침
2014 년 가져옴
2015 년 합침
2015 년 가져옴
2016 년 합침
2016 년 가져옴
2017 년 합침
2017 년 가져옴
2018 년 합침
2018 년 가져옴
2019 년 합침
2019 년 가져옴
2020 년 합침
2020 년 가져옴
2021 년 합침
2021 년 가져옴
2022 년 합침
2022 년 가져옴
2023 년 합침
2023 년 가져오다가 으악

In [44]:
girl_babyname = girl_babyname.drop(['순위'], axis = 1)

In [45]:
boy_babyname = boy_babyname.drop(['순위'], axis = 1)

In [46]:
girl_babyname

,2008년 이름,전체비율,건수,2009년 이름,전체비율,건수,2010년 이름,전체비율,건수,2011년 이름,...,건수,2020년 이름,전체비율,건수,2021년 이름,전체비율,건수,2022년 이름,전체비율,건수
0,서연,서연(7.69%),3316,서연,서연(8.25%),3553,서연,서연(8.06%),3579,서연,...,2248,서아,서아(7.61%),2191,서아,서아(8.26%),2378,서아,서아(8.57%),1696
1,민서,민서(6.71%),2892,민서,민서(7.02%),3023,서현,서현(7.28%),3231,서현,...,2012,하윤,하윤(6.86%),1977,하윤,하윤(7.24%),2086,이서,이서(8.19%),1621
2,지민,지민(6.60%),2844,서현,서현(6.32%),2723,민서,민서(6.80%),3020,서윤,...,1996,지안,지안(6.47%),1862,이서,이서(7.14%),2055,하윤,하윤(6.30%),1246
3,서현,서현(6.13%),2645,지우,지우(5.93%),2555,지우,지우(6.16%),2732,민서,...,1927,서윤,서윤(5.70%),1641,지아,지아(5.89%),1697,지아,지아(6.29%),1244
4,서윤,서윤(5.81%),2505,서윤,서윤(5.82%),2506,서윤,서윤(6.13%),2722,지우,...,1907,하은,하은(5.53%),1594,지안,지안(5.87%),1690,지안,지안(6.05%),1197
5,예은,예은(5.49%),2369,지민,지민(5.79%),2494,지민,지민(6.07%),2693,지민,...,1720,아린,아린(5.39%),1553,서윤,서윤(5.33%),1536,아윤,아윤(5.57%),1102
6,하은,하은(4.95%),2135,수빈,수빈(5.20%),2240,하은,하은(5.16%),2290,윤서,...,1651,하린,하린(5.35%),1542,아린,아린(5.28%),1521,시아,시아(5.50%),1088
7,지우,지우(4.94%),2128,하은,하은(5.20%),2239,윤서,윤서(4.92%),2182,하은,...,1569,아윤,아윤(5.25%),1512,하린,하린(5.16%),1487,서윤,서윤(5.20%),1028
8,수빈,수빈(4.88%),2103,예은,예은(4.86%),2093,수빈,수빈(4.72%),2097,지윤,...,1566,지우,지우(4.93%),1419,아윤,아윤(5.11%),1472,아린,아린(5.13%),1015
9,윤서,윤서(4.67%),2014,윤서,윤서(4.54%),1957,지윤,지윤(4.63%),2055,은서,...,1486,수아,수아(4.89%),1408,하은,하은(4.84%),1393,하린,하린(4.83%),956
10,유진,유진(4.56%),1967,민지,민지(4.35%),1875,은서,은서(4.50%),1996,채원,...,1450,시아,시아(4.77%),1374,지우,지우(4.64%),1337,지우,지우(4.72%),934
11,은서,은서(4.50%),1940,지윤,지윤(4.31%),1856,예은,예은(4.44%),1971,예은,...,1425,지아,지아(4.76%),1371,시아,시아(4.58%),1320,지유,지유(4.53%),897
12,예진,예진(4.41%),1901,예원,예원(4.25%),1832,예원,예원(4.12%),1827,다은,...,1361,나은,나은(4.73%),1363,지유,지유(4.18%),1205,하은,하은(4.09%),809
13,지윤,지윤(4.40%),1896,채원,채원(4.24%),1827,다은,다은(4.05%),1799,수빈,...,1324,지유,지유(4.72%),1359,수아,수아(3.99%),1149,유나,유나(3.97%),785
14,민지,민지(4.22%),1821,수민,수민(4.13%),1779,채원,채원(3.99%),1770,예원,...,1296,서연,서연(4.13%),1190,나은,나은(3.97%),1143,채아,채아(3.74%),740
15,예원,예원(4.22%),1820,은서,은서(4.04%),1739,지원,지원(3.92%),1739,하윤,...,1199,유나,유나(3.91%),1125,서연,서연(3.79%),1091,수아,수아(3.56%),704
16,지원,지원(4.18%),1804,가은,가은(4.01%),1725,민지,민지(3.79%),1683,지유,...,1152,예나,예나(3.85%),1110,서하,서하(3.79%),1091,서연,서연(3.49%),691
17,서영,서영(4.08%),1758,예진,예진(3.95%),1701,가은,가은(3.79%),1680,지원,...,1146,서우,서우(3.85%),1109,유나,유나(3.76%),1083,나은,나은(3.45%),682
18,수민,수민(3.88%),1671,서영,서영(3.90%),1679,서영,서영(3.75%),1665,소율,...,1118,다은,다은(3.76%),1082,서우,서우(3.65%),1050,유주,유주(3.43%),678
19,가은,가은(3.68%),1587,지원,지원(3.89%),1674,유진,유진(3.72%),1652,민지,...,1107,유주,유주(3.53%),1018,하율,하율(3.52%),1013,리아,리아(3.38%),668
20,기타,기타(81.13%),185372,기타,기타(80.57%),178615,기타,기타(80.93%),188358,기타,...,124622,기타,기타(79.32%),110460,기타,기타(78.66%),106124,기타,기타(77.87%),69622
21,NaN,NaN,228488,NaN,NaN,221685,NaN,NaN,232741,NaN,...,155282,NaN,NaN,139260,NaN,NaN,134921,NaN,NaN,89403

In [47]:
boy_babyname

,2008년 이름,전체비율,건수,2009년 이름,전체비율,건수,2010년 이름,전체비율,건수,2011년 이름,...,건수,2020년 이름,전체비율,건수,2021년 이름,전체비율,건수,2022년 이름,전체비율,건수
0,민준,민준(8.21%),2656,민준,민준(9.27%),3130,민준,민준(9.57%),3640,민준,...,2633,도윤,도윤(8.00%),2488,이준,이준(9.02%),2854,이준,이준(9.06%),1923
1,지훈,지훈(6.77%),2191,지후,지후(6.43%),2170,지훈,지훈(5.59%),2126,주원,...,2334,서준,서준(7.95%),2474,서준,서준(7.77%),2457,서준,서준(6.92%),1469
2,현우,현우(6.02%),1947,지훈,지훈(5.95%),2007,예준,예준(5.56%),2115,예준,...,2243,하준,하준(6.62%),2061,하준,하준(7.15%),2263,시우,시우(6.61%),1403
3,준서,준서(5.89%),1905,현우,현우(5.75%),1940,현우,현우(5.51%),2096,시우,...,2158,은우,은우(6.42%),1997,도윤,도윤(7.05%),2230,하준,하준(6.55%),1389
4,우진,우진(5.65%),1827,준서,준서(5.67%),1913,준서,준서(5.49%),2088,서준,...,2112,시우,시우(6.30%),1961,은우,은우(6.16%),1948,지호,지호(5.98%),1269
5,건우,건우(5.31%),1720,건우,건우(5.35%),1805,지호,지호(5.48%),2083,준서,...,1791,이준,이준(5.87%),1825,시우,시우(5.87%),1858,은우,은우(5.81%),1233
6,예준,예준(5.29%),1713,예준,예준(5.33%),1798,현준,현준(5.28%),2008,지훈,...,1749,지호,지호(5.47%),1702,지호,지호(5.13%),1623,도윤,도윤(5.58%),1183
7,현준,현준(5.03%),1627,현준,현준(5.06%),1707,건우,건우(5.18%),1971,현우,...,1677,예준,예준(4.84%),1507,예준,예준(4.72%),1494,이안,이안(5.36%),1138
8,도현,도현(4.94%),1599,우진,우진(4.65%),1568,서준,서준(5.12%),1948,도현,...,1662,유준,유준(4.54%),1412,수호,수호(4.43%),1403,선우,선우(4.88%),1036
9,준혁,준혁(4.93%),1595,민재,민재(4.57%),1544,지후,지후(5.08%),1931,지후,...,1585,건우,건우(4.19%),1303,유준,유준(4.41%),1395,유준,유준(4.52%),958
10,동현,동현(4.87%),1577,시우,시우(4.57%),1542,준혁,준혁(5.06%),1924,도윤,...,1491,주원,주원(4.18%),1301,선우,선우(4.30%),1359,수호,수호(4.48%),950
11,민재,민재(4.59%),1484,민성,민성(4.45%),1503,시우,시우(4.95%),1882,지호,...,1444,연우,연우(4.18%),1300,이안,이안(4.24%),1343,예준,예준(4.47%),949
12,서준,서준(4.57%),1479,서준,서준(4.38%),1480,준우,준우(4.37%),1662,우진,...,1417,수호,수호(4.18%),1299,로운,로운(4.13%),1306,로운,로운(4.01%),851
13,승현,승현(4.42%),1430,지호,지호(4.31%),1455,도현,도현(4.26%),1619,현준,...,1379,도현,도현(4.16%),1294,주원,주원(3.94%),1248,우주,우주(3.85%),817
14,승민,승민(4.34%),1404,도현,도현(4.30%),1453,승민,승민(4.12%),1567,민재,...,1375,민준,민준(4.13%),1286,민준,민준(3.93%),1242,주원,주원(3.80%),806
15,민성,민성(4.26%),1379,승민,승민(4.22%),1423,민재,민재(4.10%),1559,건우,...,1375,이안,이안(3.90%),1214,건우,건우(3.67%),1161,이현,이현(3.70%),786
16,시우,시우(3.86%),1249,동현,동현(4.13%),1393,우진,우진(4.02%),1530,준우,...,1303,선우,선우(3.88%),1207,준우,준우(3.66%),1157,시윤,시윤(3.70%),784
17,준영,준영(3.82%),1236,준혁,준혁(4.03%),1361,도윤,도윤(3.82%),1452,준혁,...,1284,준우,준우(3.78%),1176,연우,연우(3.54%),1119,도현,도현(3.63%),771
18,서진,서진(3.64%),1177,승현,승현(3.93%),1328,민성,민성(3.78%),1438,시후,...,1278,우진,우진(3.78%),1175,도현,도현(3.50%),1106,연우,연우(3.61%),765
19,정우,정우(3.61%),1169,준우,준우(3.65%),1233,시후,시후(3.68%),1399,승민,...,1174,서진,서진(3.63%),1130,우주,우주(3.39%),1072,우진,우진(3.47%),736
20,기타,기타(86.64%),209895,기타,기타(85.62%),200914,기타,기타(84.64%),209668,기타,...,131348,기타,기타(78.84%),115888,기타,기타(77.79%),110798,기타,기타(77.35%),72460
21,NaN,NaN,242259,NaN,NaN,234667,NaN,NaN,247706,NaN,...,164812,NaN,NaN,147000,NaN,NaN,142436,NaN,NaN,93676